# -*- coding: utf-8 -*-
"""analytica.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KtsvpI7C0GkK779QTFKDceOMX74hSZv4
"""

from google.colab import drive

drive.mount('/content/gdrive')

df = pd.read_csv('gdrive/My Drive/USvideos.csv')

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import missingno as mn
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.decomposition import PCA

sns.set(style="whitegrid")

def summary(df):
    pd.set_option('display.max_columns', 500)
    try:
        print(df.describe(include=[np.number]), '\n')
    except ValueError:
        print('', end='')
    try:
        print(df.describe(exclude=[np.number]))
    except ValueError:
        print('', end='')
    pd.set_option('display.max_columns', 5)

def head(df, full=True):
    if full:
        pd.set_option('display.max_columns', 500)
        print(df.head())
        pd.set_option('display.max_columns', 5)

    else:
        print(df.head())

def delete_cols(df, indexes):
    return df.drop(indexes, axis=1)

def aggregate(df, column, by):
    if type(by) is not list:
        tmp_df = df[[by, column]]
        pd.set_option('display.max_columns', 500)
        print(tmp_df.groupby([by]).describe())
        pd.set_option('display.max_columns', 5)
    else:
        tmp_df = df[by + [column]]
        pd.set_option('display.max_columns', 500)
        print(tmp_df.groupby(by).describe())
        pd.set_option('display.max_columns', 5)

def scatterplot(df, x, y, hue=None, size=None):
    _, ax = plt.subplots(figsize=(12, 8))
    sns.scatterplot(x, y, hue=hue, size=size, data=df, sizes=(20, 100), ax=ax)

def jointplot(df, x, y):
    sns.jointplot(x, y, kind='reg', data=df, height=8)

def histogram(df, x, bins=None):
    _, ax = plt.subplots(figsize=(12, 8))
    sns.distplot(df[x], ax=ax, bins=bins)

def boxplot(df, x=None, y=None, hue=None):
    _, ax = plt.subplots(figsize=(12, 8))
    if x is None:
        sns.boxplot(data=df, orient="h")
    elif type(x) is list:
        tmp_df = df[x]
        sns.boxplot(data=tmp_df, orient='h')
    else:
        sns.boxplot(x, y, hue=hue, data=df)

def correlation_matrix(df, figsize=(10, 10)):
    fig, ax = plt.subplots(figsize=figsize)
    sns.heatmap(df.corr(), vmax=1.0, center=0, fmt='.2f', square=True, linewidths=.5, annot=True, cbar_kws={"shrink": .70})
    plt.show()

def n():
    print('\n')

def missing_vals(df):
    cols = df.isna().sum()/df.shape[0]
    cols = pd.DataFrame({'Column name': cols.index, 'Missing %': cols.values})
    rows = (df.isna().sum(axis=1)/df.shape[1]).value_counts()
    rows = pd.DataFrame({'Missing %': rows.index, 'Quantity': rows.values})
    print('Columns:')
    print(cols)
    n()
    print('Rows: ')
    print(rows)

def missing_vals_vis(df, figsize=(8, 4)):
    _, ax = plt.subplots(figsize=figsize)
    mn.matrix(df, ax=ax)
    _, ax2 = plt.subplots(figsize=figsize)
    mn.dendrogram(df, ax=ax2)
    _, ax3 = plt.subplots(figsize=figsize)
    mn.bar(df, ax=ax3)

def drop_mostly_missing(df, col_th=0.6, row_th=0.7):
    cols = df.isna().sum()/df.shape[0]
    cols = pd.DataFrame({'name': cols.index, 'missing': cols.values})
    df_tmp = cols.loc[cols['missing'] > col_th]
    df_tmp = df_tmp['name'].values
    ret_df = delete_cols(df, df_tmp)

    rows = ret_df.isna().sum(axis=1)/ret_df.shape[1]
    rows = pd.DataFrame({'index': rows.index, 'missing': rows.values})
    rows_tmp = rows.loc[rows['missing'] > row_th]
    rows_tmp = rows_tmp['index'].values
    ret_df = ret_df.drop(rows_tmp)

    return ret_df

def fill_missing(df, cols='all', strategy='median'):
    if cols == 'all':
        imputer = SimpleImputer(missing_values=np.nan, strategy=strategy)
        imputed_df = pd.DataFrame(imputer.fit_transform(df))
        imputed_df.columns = df.columns
        imputed_df.index = df.index
        return imputed_df
    else:
        imputer = SimpleImputer(missing_values=np.nan, strategy=strategy)
        imputed_df = pd.DataFrame(imputer.fit_transform(df[cols]))
        df[cols] = imputed_df.values
        return df

def normalize(df, scaler, cols='all'):
    if cols == 'all':
        scaled_df = pd.DataFrame(scaler.fit_transform(df))
        scaled_df.columns = df.columns
        scaled_df.index = df.index
        return scaled_df
    elif cols == 'numeric':
        cols = df.select_dtypes([np.number]).columns
        scaled_df = pd.DataFrame(scaler.fit_transform(df[cols]))
        df[cols] = scaled_df.values
        return df
    else:
        scaled_df = pd.DataFrame(scaler.fit_transform(df[cols]))
        df[cols] = scaled_df.values
        return df

def standardize(df, cols='all'):
    return normalize(df, StandardScaler(), cols)

def scale(df, cols='all'):
    return normalize(df, MinMaxScaler(), cols)

def categorical_features(df, cols):
    for c in cols:
        print(c)
        print(df[c].value_counts(), '\n')

def encode_categorical_features(df, cols, drop_first=False):
    return pd.get_dummies(df, columns=cols, drop_first=drop_first)

def pca(X, y=None, plot_cumvar=True, plot_2d=False):
    pca = PCA()
    pca_result = pca.fit_transform(X)
    cumvar = np.cumsum(pca.explained_variance_ratio_)
    cumvar_df = pd.DataFrame(data = {'PCA': np.arange(1, X.shape[1]+1), 'CumVar': cumvar})

    if plot_cumvar:
        plt.plot(np.arange(1, X.shape[1]+1), cumvar)
        plt.show()

    if plot_2d and y is not None:
        plt.figure(figsize=(10,6))
        sns.scatterplot(
            x=pca_result[:, 0], y=pca_result[:, 1],
            hue=y,
            palette=sns.color_palette("hls", len(set(y))),
            legend='full',
            alpha=0.3
        )

    return pca_result, cumvar_df, pca.components_ #n_components x n_features

df = delete_cols(df, ['video_id', 'trending_date', 'title', 'channel_title', 'publish_time', 'tags', 'thumbnail_link', 'video_error_or_removed', 'description'])
summary(df)

head(df)

aggregate(df, 'likes', 'comments_disabled')

scatterplot(df, 'likes', 'dislikes', hue='comment_count')

jointplot(df, 'likes', 'comment_count')

jointplot(df, 'dislikes', 'comment_count')

histogram(df, 'views')

boxplot(df, x='comments_disabled', y='comment_count', hue='ratings_disabled')

boxplot(df)

aggregate(df, 'views', ['comments_disabled', 'ratings_disabled'])

boxplot(df, x=['likes', 'dislikes'])

df = pd.read_csv('https://raw.githubusercontent.com/suchy1713/EmotionPredicition/master/data/preprocessed/merged.csv')

#drop emospace answers
df = df.drop(df[df['WIDGET-TYPE'] == 'emospace1'].index)

#drop useless features
df = df.drop(['TIMESTAMP', 'WIDGET-TYPE', 'COND', 'ANS-TIME', 'IADS-ID', 'IAPS-ID', 'ID', 'PROCEDURE-BEGIN-TIMESTAMP', 'PROCEDURE-END-TIMESTAMP', 'BIOSIGS-BEGIN-TIMESTAMP', 'BIOSIGS-END-TIMESTAMP', 'NEO-FFI', 'BIOSIGS', 'PROCEDURE', 'SPACE', 'FREUD', 'PHOTOS'], axis=1)

df = df.assign(NEUROTICISM=np.nan)
df = df.assign(OOO=np.nan)

missing_vals(df)

df = drop_mostly_missing(df)

missing_vals(df)

df = fill_missing(df, cols=['OPENNESS', 'AGE', 'CONSCIENTIOUSNESS', 'EXTRAVERSION', 'AGREEABLENESS'])
missing_vals(df)

summary(df)

categorical_features(df, ['category_id', 'comments_disabled', 'ratings_disabled'])

df = encode_categorical_features(df, ['category_id'])
df = encode_categorical_features(df, ['comments_disabled', 'ratings_disabled'], drop_first=True)
summary(df)

df = standardize(df)
summary(df)

correlation_matrix(df, figsize=(15,15))

pca_result, var, comp = pca(df)
print(var)
#print(comp)

x = df.drop(columns=['comments_disabled_True'])
y = df['comments_disabled_True']

res, var, _ = pca(x, y, plot_2d=True)